apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: Arena MySQL
    uid: arena-mysql
    type: mysql
    access: proxy
    url: mysql:3306
    database: arena_agent
    user: ${MYSQL_USERNAME}
    secureJsonData:
      password: ${MYSQL_PASSWORD}
    jsonData:
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
